In [1]:
import numpy as  np

In [2]:
un = np.array([0.3**3 * .7, 0.5**2 * .2, 0.6**2 * .4 * .5])
un / un.sum()

array([0.13413769, 0.3548616 , 0.51100071])

In [3]:
un

array([0.0189, 0.05  , 0.072 ])

In [5]:
un = np.array([3**3 * 7, 5**3 * 2, 6**2 * 4 * 5])
un / un.sum()

array([0.16307161, 0.21570319, 0.62122519])

In [6]:
189/1159

0.1630716134598792