In [1]:
import numpy as  np

In [2]:
un = np.array([0.3**3 * .7, 0.5**2 * .2, 0.6**2 * .4 * .5])
un / un.sum()

array([0.13413769, 0.3548616 , 0.51100071])

In [3]:
un

array([0.0189, 0.05  , 0.072 ])

In [4]:
un = np.array([3**3 * 7, 5**3 * 2, 6**2 * 4 * 5])
un / un.sum()

array([0.16307161, 0.21570319, 0.62122519])

In [5]:
189/1159

0.1630716134598792

In [6]:
def Rmat(theta):
 rad = np.radians(theta)
 c,s = np.cos(rad), np.sin(rad)
 R_matrix = np.array(((c, -s,0), (s, c,0), (0,0,1)))
 return R_matrix

def Tmat(a, b):
 M_matrix = np.array(((1,0,a),(0,1,b),(0,0,1)))
 return M_matrix

In [7]:
a, b = 500, 400
H = Tmat(a, b) @ Rmat(45) @ Tmat(-a, -b)
H

array([[   0.70710678,   -0.70710678,  429.28932188],
       [   0.70710678,    0.70710678, -236.39610307],
       [   0.        ,    0.        ,    1.        ]])