In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch as th

In [2]:
th.__version__

'1.8.1+cu102'

# Example 6.2

### What is the true state value at each location?

In [23]:
A = np.array([[2., -1, 0, 0, 0],
              [-1, 2, -1, 0, 0],
              [0, -1, 2, -1, 0],
              [0, 0, -1, 2, -1],
              [0, 0, 0, -1, 2]])
b = np.array([0., 0, 0, 0, 1])

In [24]:
det = np.linalg.det(A)
det

6.0

In [25]:
Ainv = np.linalg.inv(A)
V = Ainv @ b
V * det

array([1., 2., 3., 4., 5.])

In [26]:
a = th.tensor(A); a

tensor([[ 2., -1.,  0.,  0.,  0.],
        [-1.,  2., -1.,  0.,  0.],
        [ 0., -1.,  2., -1.,  0.],
        [ 0.,  0., -1.,  2., -1.],
        [ 0.,  0.,  0., -1.,  2.]], dtype=torch.float64)

In [30]:
th.inverse(a) @ th.tensor(b) * 6

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.0000], dtype=torch.float64)