# Mid-term Exam

1. Submit your jupyter notebook
1. Submit a pdf version of your jupyter notebook
    - By submitting a pdf version, you will get some extra points.
    - Simply click the button, and you will have a pdf version.
        - In some cases you need to install [jupyter_contrib_nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html) before you click the button.
    
            - ```pip install jupyter_contrib_nbextensions```
            - Be aware that you might need to use `pip3.8` or something equivalent instead of `pip`.

    - If pdf is not created due to some problems, you may make screen shots that cover the whole notebook and submit them instead. The exam questions in those parts that are not included in the screen shots will be regarded as not-solved and will be given zero scores. Extra points are not provided, either.

Warnings:

1. You may use internet search engines such as google or stackoverflow to get help on-line.
1. Failure of uploading the solution copy is your responsibility.
1. You must not communicate with any living creature.
1. You must not talk.

# Q1. Make a python code that prints out your name and student id number (학번)

Your solution must be provided in the following cell.

In [1]:
# your program must be provided here.

# Q2. Make a function tha computes the sum of the numbers in the list.

In [2]:
input_list = [1, 3, 5, 7, 9]

In [3]:
def sum_function(in_list):  # do not change the function definition
    # your program must be provided below.
    pass

In [4]:
print(sum_function(input_list))

None


End.

# Q3. Age difference
Your function takes two arguments:

1. current father's age (years)
2. current age of his son (years)

Сalculate how many years ago the father was twice as old as his son (or in how many years he will be twice as old).

In [5]:
def twice_as_old(dad, son):  # do not change function definition. 
    # your solution here
    pass

In [6]:
print(twice_as_old(36, 7))  # output must be 22

None


In [7]:
print(twice_as_old(22, 1))  # output must be 20

None


# Q4. Add Two Arrays

Create a function called `addTwoArrays()` that combines two arrays of equal length, summing each element of the first with the corresponding element in the second, returning the "combined" summed array.

In [8]:
def addTwoArrays(a, b):
    pass

In [9]:
print(addTwoArrays([1, 2], [3, 4]))  # => [4, 6]

None


In [10]:
print(addTwoArrays(['a'], ['b']))  # => ['ab']

None


# Q5. Binary Number

Given an array of ones and zeroes, convert the equivalent binary value to an integer.

Eg: `[0, 0, 0, 1]` is treated as 0001 which is the binary representation of 1.
- Testing: `[0, 0, 1, 0]` ==> 2
- Testing: `[0, 1, 0, 1]` ==> 5
- Testing: `[1, 0, 0, 1]` ==> 9


In [11]:
def binary2int(array):
    pass

In [12]:
print(binary2int([0,0,1,0]))

None


In [13]:
b = [1, 0, 0, 0, 1]
n = binary2int(b)
print(f'N={n} for b={b}')

N=None for b=[1, 0, 0, 0, 1]


# Q6. Miles to kilometers

Sometimes, I want to quickly be able to convert miles per imperial gallon into kilometers per liter.

Create an application that will display the number of kilometers per liter (output) based on the number of miles per imperial gallon (input).

Make sure to round off the result to two decimal points. If the answer ends with a 0, it should be rounded off without the 0. So instead of 5.50, we should get 5.5.

Some useful associations relevant to this kata: 1 Imperial Gallon = 4.54609188 litres 1 Mile = 1.609344 kilometres

In [14]:
def miles2km(mile_per_gallon):
    pass

In [15]:
print( miles2km(12) )  # => 4.25

None


In [16]:
print( miles2km(36) )  # => 12.74

None


# Q7. Rock Paper Scissors

The function has to return which player won! In case of a draw return `Draw!`

In [17]:
def rps_play (player1, player2):
    pass

In [18]:
print(rps_play('rock', 'scissors'))  # 'player 1 won!'

None


In [19]:
print(rps_play('paper', 'paper'))  # 'Draw!'

None


In [20]:
print(rps_play('scissors', 'rock'))  # 'player 2 won!'

None


# Q8. Character Counter.

Make a function `char_count(char, string)` that calculates how many times the character appears in the given text.

For example, 
- `char_count('o', 'hello')` returns 1 because 'hello' has one occurance of 'o'
- `char_count('d', 'good morning dear')` returns 2 because there are two 'd's in the input string.

In [21]:
def char_count(char, string):
    # your code here
    pass 

In [22]:
# do not toch this string!
string_pride = '''It is a truth universally acknowledged, that a single man in
      possession of a good fortune, must be in want of a wife.

      However little known the feelings or views of such a man may be
      on his first entering a neighbourhood, this truth is so well
      fixed in the minds of the surrounding families, that he is
      considered the rightful property of some one or other of their
      daughters.

      “My dear Mr. Bennet,” said his lady to him one day, “have you
      heard that Netherfield Park is let at last?”

      Mr. Bennet replied that he had not.

      “But it is,” returned she; “for Mrs. Long has just been here, and
      she told me all about it.”

      Mr. Bennet made no answer.

      “Do you not want to know who has taken it?” cried his wife
      impatiently.

      “_You_ want to tell me, and I have no objection to hearing it.”

      This was invitation enough.

      “Why, my dear, you must know, Mrs. Long says that Netherfield is
      taken by a young man of large fortune from the north of England;
      that he came down on Monday in a chaise and four to see the
      place, and was so much delighted with it, that he agreed with Mr.
      Morris immediately; that he is to take possession before
      Michaelmas, and some of his servants are to be in the house by
      the end of next week.'''

In [23]:
print( char_count('i', string_pride))

None


In [24]:
string_soho = '''
  임아행과 상문천은 상황이  불리하게 전개되자 장검과 채찍을 휘
두르며 동시에 협공을 하였다. 당세의  삼대 고수가 연합해서 싸움
을 하자 그  위세가 대단하기 짝이 없었다.  그러나 동방불패는 두 
개의 손가락으로 한 개의 수바늘을  거머쥐고 이리 뚫고 저리 지나
가고 동작이  질풍과 같았고, 처지는 기색은  전혀 보이지 않았다. 
상관운은 단도를 뽑아 앞으로 달려나가  가세를 하였다. 한참 어지
럽게 싸움을  하고 있는데 갑자기 상관운이  외치는 소리가 들려왔
다. 단도가 떨어지고 재주를 한번  넘더니 뒤로 벌렁 자빠졌다. 우
측 눈은 이미 동방불패에게 찔려서 두 손으로 우측 눈을 감싸고 있
었다.
  영호충은 임아행과 상문천, 두 사람의 공격이 날카롭자 동방불패
가 자기에게 공격해 들어오는 것이  늦추어지는 것을 보고 즉시 장
검을 움직여 그의  몸의 급소를 향해 있는  힘을 다해서 내리쳤다. 
그러나 동방불패의 몸은 마치 귀신처럼  이리 날고 저리 날고 마치 
연기와 같았다. 영호충의  검끝은 도저히 그의 몸에  갖다 댈 수가 
없었다. 갑자기 상문천이 악 하고 외마디 소리를 지르고 이어서 영
호충도 훅 하고 소리를 질렀다. 두  사람의 몸이 각기 바늘에 적중
된 것이다. 임아행이 연마한 흡성대법은 깊지만 그러나 동방불패의 
몸놀림은 너무 빨라 몸을 접촉할  수가 없으며 또한 사용하는 병기
가 아주 적은 수바늘이어서 바늘끝에서  그의 내공의 흡수 할 도리
가 없었다.
  또 한참 동안  싸움을 하였다. 임아행 역시 악 하고 외마디 소리
를 질렀다. 가슴과 목덜미에는 바늘이꽂혔다. 다행이 영호충은 급
하게 공격을 했기 때문에 동방불패는 자신을 비방하느라 바늘 하나
를 잘못 날렸고 또 다른 바늘 하나는 정확하게 와서 꽂혔지만 그리 
치명상을 줄 정도는 아니었다.
  네 사람이 동방불패를 에워싸고 공격했으나 그의 옷자락 하나 부
딪칠 수가 없었다. 그러나 네 사람은  모두 그의 바늘에 맞았던 것
이다. 영영은 옆에서 관전을 하다가 갈수록 걱정이 되었다.
'''

In [25]:
print( char_count('동', string_soho))

None


In [26]:
string_laodong = """
Đề xuất của Bộ Lao động, Thương binh và Xã hội rất có lợi cho người lao động. Tất nhiên, nếu đóng với thời gian ngắn hơn, người lao động phải chấp nhận hưởng mức lương hưu ít hơn” - ông Thọ nhận định.

Khi phóng viên đặt câu hỏi, việc người lao động được nhận lương hưu sớm có gây ảnh hưởng đến việc cân bằng quỹ BHXH hay không? Ông Thọ cho biết, đây cũng là bài toán về cách tính hưởng lương hưu một khi đề xuất của Bộ Lao động, Thương binh và Xã hội được các cơ quan chức năng đồng ý.

“Bộ Lao động, Thương binh và Xã hội đã có đề xuất thì chắc bộ sẽ có phương án để thay đổi cách tính lương hưu cho hợp lý, đảm bảo quỹ BHXH không bị ảnh hưởng. Theo tôi, Ban soạn thảo cần phải tính toán, nghiên cứu kỹ số năm đóng và số năm hưởng để đưa ra công thức tính lương hưu cho phù hợp” - ông Thọ nêu ý kiến.

Theo thạc sĩ Luật Uông Quang Huy - Phó Chủ tịch Công đoàn Điện lực Việt Nam, hiện nay, việc tiếp cận với chính sách lương hưu của người lao động khi về già là quá khó khăn khi điều kiện về số năm đóng BHXH quá dài (20 năm) và đặc biệt sau khi nâng tuổi nghỉ hưu từ năm 2021.
"""

In [27]:
print( char_count('v', string_laodong))

None


In [28]:
string_Dostoevsky = """
Новости
07 апреля 2021
Курс лекций «Достоевский и дары смерти, или Краткий курс обретения бессмертия»
15 апреля — 27 мая 2021
19:00 — 20:30

Гостиный двор, ул. Ильинка, 4, аудитория 271

В 2021 году культурное сообщество России отметит 200-летний юбилей Ф. М. Достоевского. Во всем мире Достоевский сегодня один из самых цитируемых и переводимых русских авторов. Его художественное наследие изучается литературоведами, по произведениям писателя ставят спектакли, снимают фильмы. В то же время ни об одном из классиков литературы не высказано столько противоречивых суждений.

Объединение «Манеж» совместно с лекторием «Достоевский» и компанией Storytel запускает курс лекций писателя и педагога Гаянэ Степанян, который призван расширить наши знания о личности классика для более глубокого понимания его произведений.

Расписание:

15 апреля. Лекция 1. «Легенда о Великом читателе (У кого он учился)»

Достоевский — это не только великий писатель, он великий читатель. Отдавая должное всемирной природе Пушкина, он и сам обладал такою же природой: это значит, что прочитанные книги переплавлялись в его творчестве, обретали собственные голоса, становились способами разоблачить несостоятельность идей героев и поддержать голос автора. Охватить весь круг чтения великого писателя мы, конечно, в рамках часовой лекции не сможем. Мы затронем ключевые имена предшественников, таких, как Пушкин, и проанализируем, как Достоевский включает в свои произведения эти тексты и как их обыгрывает, чтоб дать читателю не готовые ответы, но ключи к пониманию авторской позиции: в отличие от Льва Николаевича, Достоевский никогда не дает своему читателю интеллектуального преимущества над заблуждающимся героем.
"""

In [29]:
print( char_count('Д', string_Dostoevsky) )

None


# Q9. Calculate the sum of the unicodes of all the characters in the string.

In [30]:
def unicode_sum(string):
    pass

In [31]:
n1 = unicode_sum(string_pride)
print(f'The sum of unicodes of the string is ', n1)

The sum of unicodes of the string is  None


In [32]:
n2 = unicode_sum(string_laodong)
print(f'The sum of unicodes of the string is ', n2)

The sum of unicodes of the string is  None


In [33]:
n3 = unicode_sum(string_soho)
print(f'The sum of unicodes of the string is ', n3)

The sum of unicodes of the string is  None


In [34]:
n4 = unicode_sum(string_Dostoevsky)
print(f'The sum of unicodes of the string is ', n4)

The sum of unicodes of the string is  None


In [35]:
# Do not touch!
# It will produce proper output when your function is ready, and will be used for checking the functioning of your function.
print(f'The sum of all the 4 sums is {n1 + n2 + n3 + n4}')

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

# Q10. Traffic light
You're writing code to control your town's traffic lights. You need a function to handle each change from `green`, to `yellow`, to `red`, and then to `green` again.

Complete the function that takes a string as an argument representing the current state of the light and returns a string representing the state the light should change to.

For example, update_light('green') should return 'yellow'.

In [69]:
def update_light(current_light):
    # your code
    pass

In [71]:
print(update_light('green'))  # => 'yellow'

None


In [72]:
print(update_light('red'))  # => 'green'

None


In [73]:
print(update_light('yellow'))  # => 'red

None


# Extra 1. Traffic light with python's dictionary data type

Make another version of `update_light()` that uses dictionary.

Correctly solving this problem gives you extra point.

In [38]:
def update_light_dictionary(current_light):
    # use python dictionary to solve this problem.
    pass

In [75]:
print(update_light_dictionary('green'))

None


In [76]:
print(update_light_dictionary('yellow'))

None


In [77]:
print(update_light_dictionary('red'))

None


# Extra 2. Submit PDF version of your jupyter notebook.

- This will give you extra points.

- Simply click the button, and you will have a pdf version.
    - In some cases you need to install [jupyter_contrib_nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html) before you click the button.

        - ```pip install jupyter_contrib_nbextensions```
        
        - Be aware that you might need to use `pip3.8` or something equivalent instead of `pip`.


---
# End.

Check.

* You must provide a correct solution for Q1. Otherwise, you will fail.



**Warnings**
- No cheating is allowed. 
- On sight cheating will result in F. 
- If any report about bad behavoirs of someone is reported, the person will be asked to have an additional face-to-face oral examination to test his/her skill level of python programming. If the level is not found to match the expectation given by the exam score, his/her final grade will result in F. 

In [36]:
import numpy as np 

a = np.arange(0, 10)
t = a < 5
t

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [39]:
f = ~t
f

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
t.astype(np.int32)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])