# Linear Gaussian System
Example of Sensor find_distributions

Ref:
1. Prml book 2, Chap. 2.2.6.3, Figure 2.8

In [1]:
import numpy as np
import matplotlib.pyplot as plt 

In [6]:
uz = np.array([0, 0])
Cz = np.eye(2) * 1000000 # almost uniform
W = np.array([ [1,0,1,0], [0,1,0,1]]).T 
Cx = np.eye(2)*0.01
Cy = np.eye(2)*0.01 
W, Cx, Cy
obsx = np.array([0, -1])
obsy = np.array([1, 0])

In [15]:
# compute posterior p(z|x,y)

v = np.concatenate((obsx, obsy)); v
Cv = np.eye(4); Cv[:2,:2] = Cx; Cv[2:,2:]=Cy; Cv 

S = Cv + W @ Cz @ W.T 
Sinv = np.linalg.inv(S)
uzc = uz + Cz @ W.T @ Sinv @ (v - W @ uz)
Czc = Cz - Cz @ W.T @ Sinv @ W @ Cz 

In [36]:
# posterior mean and cov
u, Czc

(array([ 0.5, -0.5]),
 array([[0.00126238, 0.        ],
        [0.        , 0.00126238]]))

In [20]:
np.linalg.eig(Czc)

(array([0.00126238, 0.00126238]),
 array([[1., 0.],
        [0., 1.]]))

In [32]:
A = np.array([[10, 1], [1, 1]])
w, v = np.linalg.eig(A)
w, v

(array([10.10977223,  0.89022777]),
 array([[ 0.99402894, -0.10911677],
        [ 0.10911677,  0.99402894]]))

In [33]:
v @ np.diag(w) @ v.T

array([[10.,  1.],
       [ 1.,  1.]])

In [35]:
v
angle = np.arctan2(v[1,0], v[0,0]) * 180 / np.pi
angle , "degrees"

(6.264403854575756, 'degrees')

## Second Example

In [37]:
uz = np.array([0, 0])
Cz = np.eye(2) * 1000000 # almost uniform
W = np.array([ [1,0,1,0], [0,1,0,1]]).T 
Cx = np.eye(2)*0.05
Cy = np.eye(2)*0.01 
W, Cx, Cy
obsx = np.array([0, -1])
obsy = np.array([1, 0])

In [39]:
# compute posterior p(z|x,y)

v = np.concatenate((obsx, obsy)); v
Cv = np.eye(4); Cv[:2,:2] = Cx; Cv[2:,2:]=Cy; Cv 

S = Cv + W @ Cz @ W.T 
Sinv = np.linalg.inv(S)
uzc = uz + Cz @ W.T @ Sinv @ (v - W @ uz)
Czc = Cz - Cz @ W.T @ Sinv @ W @ Cz 

uzc, Czc

(array([ 0.83333332, -0.16666667]),
 array([[0.01000285, 0.        ],
        [0.        , 0.01000285]]))

## Third Example

In [41]:
uz = np.array([0, 0])
Cz = np.eye(2) * 1000000 # almost uniform
W = np.array([ [1,0,1,0], [0,1,0,1]]).T 
Cx = np.array([[10, 1], [1,1]])*0.01
Cy = np.array([[1, 1], [1,10]])*0.01 
W, Cx, Cy
obsx = np.array([0, -1])
obsy = np.array([1, 0])

In [42]:
# compute posterior p(z|x,y)

v = np.concatenate((obsx, obsy)); v
Cv = np.eye(4); Cv[:2,:2] = Cx; Cv[2:,2:]=Cy; Cv 

S = Cv + W @ Cz @ W.T 
Sinv = np.linalg.inv(S)
uzc = uz + Cz @ W.T @ Sinv @ (v - W @ uz)
Czc = Cz - Cz @ W.T @ Sinv @ W @ Cz 

uzc, Czc

(array([ 0.84615384, -0.84615384]),
 array([[0.00769944, 0.00173027],
        [0.00168669, 0.00946761]]))