In [26]:
import pygame as pg 
import numpy as np 


def getHomogeneous(p_aff):
    """ p_aff: N x 2 affine coordinates, each row being a 2D coordinate vector """
    ones = np.ones( (p_aff.shape[0], 1) )
    p_homo = np.hstack( (p_aff, ones) )
    return p_homo
#

class Polygon:
    def __init__(self, vertices, color=(255,255,200)):
        """ vertices: N x 2 point coordinates for a proper polygon """
        self.vertices_h = getHomogeneous(vertices)  # must be 
        self.vertices = self.vertices_h[:,:2]
        self.color = color            
    def transform(self, H):  # or update()
        """ vertices = H @ vertices """
        
        self.vertices_h = H @ self.vertices_h.T
        self.vertices_h = self.vertices_h.T 
        
        
    def draw(self, screen):
        pg.draw.polygon(screen, self.color, self.vertices)

In [27]:
p = np.array([ [2, 2], [5, 2], [5, 5], [3, 5], [2, 3]])
p.shape

(5, 2)

In [28]:
ones = np.ones((p.shape[0], 1))
ones.shape

(5, 1)

In [29]:
p_homo = np.hstack( (p, ones) )
p_homo, p_homo.shape

(array([[2., 2., 1.],
        [5., 2., 1.],
        [5., 5., 1.],
        [3., 5., 1.],
        [2., 3., 1.]]),
 (5, 3))

In [30]:
p_homo.T 

array([[2., 5., 5., 3., 2.],
       [2., 2., 5., 5., 3.],
       [1., 1., 1., 1., 1.]])

In [39]:
poly = Polygon(p)

In [40]:
poly.vertices

array([[2., 2.],
       [5., 2.],
       [5., 5.],
       [3., 5.],
       [2., 3.]])

In [41]:
poly.vertices_h

array([[2., 2., 1.],
       [5., 2., 1.],
       [5., 5., 1.],
       [3., 5., 1.],
       [2., 3., 1.]])

In [42]:
H = np.eye(3)
H[0,2] = 1 # translation along X
poly.transform(H)
poly.vertices_h

array([[3., 2., 1.],
       [6., 2., 1.],
       [6., 5., 1.],
       [4., 5., 1.],
       [3., 3., 1.]])

In [43]:
poly.vertices

array([[2., 2.],
       [5., 2.],
       [5., 5.],
       [3., 5.],
       [2., 3.]])

In [44]:
H

array([[1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
H @ poly.vertices_h.T 

array([[4., 7., 7., 5., 4.],
       [2., 2., 5., 5., 3.],
       [1., 1., 1., 1., 1.]])